apply plugin: 'com.android.application'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

android {

    /*signingConfigs {
        release {
            storeFile file('/Users/onion15/Documents/MyProjects/jumbledwords/jumbled_keystore.jks')
            storePassword 'anupriya'
            keyAlias = 'key0'
            keyPassword 'anupriya'
        }
    }*/
    compileSdkVersion 29
    buildToolsVersion "29.0.0"

    defaultConfig {
        applicationId "com.stupendous.jumbledwords"
        minSdkVersion 17
        targetSdkVersion 29
        versionCode 7
        versionName "1.2.2.1"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'com.google.android.gms:play-services-ads:19.1.0'
    implementation "androidx.core:core-ktx:+"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.19'

    // Room
    implementation 'android.arch.persistence.room:runtime:1.1.1'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    kapt 'android.arch.persistence.room:compiler:1.1.1'
    implementation 'androidx.room:room-runtime:2.2.5'
    kapt 'androidx.room:room-compiler:2.2.5'
}
repositories {
    mavenCentral()
}
